### ISSUE TITLE
Running from NPX is broken after latest antlr4 release

### ISSUE THREAD

**Issue by gerson23** [thekiwi/ksql-lint#2]
After latest antlr4 release, a fresh install from ksql-lint is broken:

```
npx ksql-lint            
file:///Users/gerson/.npm/_npx/2f8f8ae7b291844e/node_modules/ksql-lint/lib/SqlBaseParser.js:820
const sharedContextCache = new antlr4.PredictionContextCache();
                           ^

TypeError: antlr4.PredictionContextCache is not a constructor
    at file:///Users/gerson/.npm/_npx/2f8f8ae7b291844e/node_modules/ksql-lint/lib/SqlBaseParser.js:820:28
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

Node.js v19.6.0
```

After some investigation, that is due to a incompatibility between antlr4 4.10.x and 4.12.x versions. The code generated from `generate.sh` is using 4.10 whereas npm is fetching 4.12.

Possible fixes are bumping up antlr4 version on package.json or just rebuilding it.

**Comment by thekiwi** [comment]
Good spot, thanks for the contribution! I've merged your PR. I've also pinned the Docker image version to 4.12 to match the NPM version. A new version (1.0.1) has been published on NPM.
